openapi: 3.0.2
info:
  title: Bank Argent - API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
tags:
  - name: account
    description: Everything about your accounts
  - name: transaction
    description: Everything about your transactions
paths:
  /account:
    get:
      tags:
        - account
      summary: List Accounts
      description: Returns Accounts associated with user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: 'Unauthorized: User credentials are invalid or missing'
        '404':
          description: 'Not Found: The Requested resource could not be found'
        '500':
          description: 'Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request'
  /account/{accountId}:
    get:
      tags:
        - account
      summary: Find Account by ID
      description: Returns a single Account
      parameters:
        - name: accountId
          in: path
          description: ID of account to get
          required: true
          schema:
            type: integer
            format: int64
            example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: 'Bad Request: The server could not understand the request due to invalid syntax or missing parameters'
        '401':
          description: 'Unauthorized: User credentials are invalid or missing'
        '403':
          description: 'Forbidden: User is not allowed to access the requested resource'
        '404':
          description: 'Not Found: The Requested resource could not be found'
        '500':
          description: 'Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request'
  /transaction/findByMonth:
    get:
      tags:
        - transaction
      summary: Find Transactions by month
      description: Returns Transactions filtered by month
      parameters:
        - name: month
          in: query
          description: Month to filter by
          required: true
          schema:
            type: string
            format: string
            example: '2022-12'
        - name: accountId
          in: query
          description: Account to get the transactions from
          required: false
          schema:
            type: integer
            format: int64
            example: 8349
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: 'Bad Request: The server could not understand the request due to invalid syntax or missing parameters'
        '401':
          description: 'Unauthorized: User credentials are invalid or missing'
        '403':
          description: 'Forbidden: User is not allowed to access the requested resource'
        '404':
          description: 'Not Found: The Requested resource could not be found'
        '500':
          description: 'Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request'
  /transaction/{transactionId}:
    get:
      tags:
        - transaction
      summary: Find Transaction by ID
      description: Returns a single Transaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to get
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: 'Bad Request: The server could not understand the request due to invalid syntax or missing parameters'
        '401':
          description: 'Unauthorized: User credentials are invalid or missing'
        '403':
          description: 'Forbidden: User is not allowed to access the requested resource'
        '404':
          description: 'Not Found: The Requested resource could not be found'
        '500':
          description: 'Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request'
    put:
      tags:
        - transaction
      summary: Update Transaction
      description: Updates an existing Transaction by ID
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to update
          required: true
          schema:
            type: integer
            format: int64
            example: 10
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  format: string
                  example: Food
                notes:
                  type: string
                  format: string
                  example: Croissant for breakfast
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: 'Bad Request: The server could not understand the request due to invalid syntax or missing parameters'
        '401':
          description: 'Unauthorized: User credentials are invalid or missing'
        '403':
          description: 'Forbidden: User is not allowed to access the requested resource'
        '404':
          description: 'Not Found: The Requested resource could not be found'
        '500':
          description: 'Internal Server Error: The server encountered an unexpected condition that prevented it from fulfilling the request'
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 8349
        name:
          type: string
          format: string
          example: Argent Bank Checking
        balance:
          type: number
          format: float
          example: 2,082.79
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        accountId:
          type: integer
          format: int64
          example: 8349
        datetime:
          type: string
          format: date-time
          example: '2020-06-20 10:26:49.219717'
        description:
          type: string
          format: string
          example: Golden Sun Bakery
        amount:
          type: number
          format: float
          example: 5.00
        type:
          type: string
          format: string
          example: Electronic
        category:
          type: string
          format: string
          example: Food
        notes:
          type: string
          format: string
          example: Croissant for breakfast
security:
  - Bearer: []
